from __future__ import annotations

from datetime import datetime
from typing import List

from ..spec.model import SkillSpec, WorkflowStep


def _render_steps(steps: List[WorkflowStep]) -> str:
    out = []
    for i, s in enumerate(steps, start=1):
        out.append(f"### Step {i} — {s.title}")
        if s.kind:
            out.append(f"*Type:* `{s.kind}`")
        if s.notes:
            out.append(s.notes)
        if s.commands:
            out.append("\n```bash")
            out.extend(s.commands)
            out.append("```\n")
    return "\n".join(out)


def _render_resources(spec: SkillSpec) -> str:
    lines = []
    if spec.references:
        lines.append("## References (loaded on-demand)")
        for p in spec.references:
            lines.append(f"- `{p}`")
        lines.append("")
    if spec.scripts:
        lines.append("## Scripts (deterministic tools)")
        for p in spec.scripts:
            lines.append(f"- `{p}`")
        lines.append("")
    if spec.assets:
        lines.append("## Assets")
        for p in spec.assets:
            lines.append(f"- `{p}`")
        lines.append("")
    return "\n".join(lines)


def _render_footer() -> str:
    ts = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    return f"\n---\nGenerated by ai-skill-creator at {ts}.\n"
