from __future__ import annotations

from ..spec.model import SkillSpec


def render_windsurf_workflow_md(spec: SkillSpec) -> str:
    """
    Render Windsurf workflow markdown (PRIMARY target).
    
    Follows ui-ux-pro-max patterns:
    - Clear workflow steps with numbered sections
    - Gate steps marked with 🚦
    - References expanded to full paths
    - Deterministic tools section for scripts
    """
    # YAML frontmatter
    lines = [
        "---",
        f"description: {spec.description}",
        "auto_execution_mode: 3",
        "---",
        "",
        f"# {spec.name}",
        "",
        spec.description,
        "",
    ]

    # Prerequisites (if scripts exist or libraries are used)
    has_prerequisites = spec.scripts or (hasattr(spec, 'libraries') and spec.libraries)
    if has_prerequisites:
        lines.extend([
            "## Prerequisites",
            "",
        ])
        
        # Show Python version check
        if spec.scripts:
            lines.extend([
                "```bash",
                "python3 --version || python --version",
                "```",
                "",
            ])
        
        # Show recommended libraries
        if hasattr(spec, 'libraries') and spec.libraries:
            lines.append("**推荐的第三方库**:")
            lines.append("")
            for lib in spec.libraries:
                if isinstance(lib, dict):
                    lib_name = lib.get('name', '')
                    lib_purpose = lib.get('purpose', '')
                    lib_pypi = lib.get('pypi_link', '')
                    lines.append(f"- `{lib_name}`: {lib_purpose}")
                    if lib_pypi:
                        lines.append(f"  - 安装: `pip install {lib_name}`")
                        lines.append(f"  - PyPI: {lib_pypi}")
                else:
                    lines.append(f"- `{lib}`")
            lines.append("")
            lines.extend([
                "```bash",
                "# 安装所有依赖",
                "pip install " + " ".join([lib.get('name', lib) if isinstance(lib, dict) else lib for lib in spec.libraries]),
                "```",
                "",
            ])

    # Triggers
    if spec.triggers:
        lines.append("## Triggers")
        lines.append("")
        for t in spec.triggers:
            lines.append(f"- {t}")
        lines.append("")

    # How to Use (for skill-creator specifically)
    is_skill_creator = spec.name == "skill-creator"
    if is_skill_creator:
        lines.extend([
            "## How to Use This Workflow",
            "",
            "When user requests skill creation (create, build, generate, update), follow this workflow:",
            "",
        ])

    # Workflow
    lines.append("## Workflow")
    lines.append("")
    lines.append(f"Mode: `{spec.workflow_type}`")
    lines.append("")
    
    for i, step in enumerate(spec.steps, start=1):
        kind_badge = " 🚦 GATE" if step.kind == "gate" else ""
        lines.append(f"### Step {i}: {step.title}{kind_badge}")
        lines.append("")
        
        if step.notes:
            notes = step.notes
            # Expand references paths
            notes = notes.replace("`references/", f"`skills/{spec.name}/references/")
            lines.append(notes)
            lines.append("")
        
        if step.commands:
            lines.append("```bash")
            for cmd in step.commands:
                lines.append(cmd)
            lines.append("```")
            lines.append("")

    # References section
    if spec.references:
        lines.append("## References")
        lines.append("")
        for ref in spec.references:
            ref_path = f"skills/{spec.name}/{ref}"
            lines.append(f"- `{ref_path}`")
        lines.append("")

    # Deterministic tools (for skill-creator)
    if is_skill_creator:
        lines.extend([
            "## Search & Generate Tools",
            "",
            "```bash",
            "# Search skill patterns and get recommendations",
            'python3 .shared/skill-creator/scripts/search.py "<keywords>" --skill-system -p "<name>"',
            "",
            "# Generate Windsurf workflow (primary target)",
            "python3 .shared/skill-creator/scripts/generate.py skills/<skill>/skillspec.json",
            "",
            "# Generate all targets (backward compat)",
            "python3 .shared/skill-creator/scripts/generate.py skills/<skill>/skillspec.json --all",
            "",
            "# Validate spec and outputs",
            "python3 .shared/skill-creator/scripts/validate.py skills/<skill>/skillspec.json",
            "",
            "# Package Claude .skill",
            "python3 .shared/skill-creator/scripts/package.py --target claude --skill <skill>",
            "```",
            "",
        ])

    # Footer
    lines.extend([
        "---",
        "",
        f"*Generated by skill-creator. Source: `skills/{spec.name}/skillspec.json`*",
    ])

    return "\n".join(lines)
