#!/usr/bin/env python3
"""
Skill Generator - Generate multi-assistant outputs from skillspec.json

Primary target: Windsurf (with backward compatibility for Claude/Cursor/GitHub)

Usage:
    python3 .shared/skill-creator/scripts/generate.py skills/<skill>/skillspec.json
    python3 .shared/skill-creator/scripts/generate.py skills/<skill>/skillspec.json --target windsurf
    python3 .shared/skill-creator/scripts/generate.py skills/<skill>/skillspec.json --all
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path
from typing import Any, Dict, List

SCRIPT_DIR = Path(__file__).parent
REPO_ROOT = SCRIPT_DIR.parent.parent.parent  # .shared/skill-creator/scripts -> repo root


def load_spec(spec_path: Path) -> Dict[str, Any]:
    return json.loads(spec_path.read_text(encoding="utf-8"))


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def copytree_safe(src: Path, dst: Path) -> None:
    """Copy directory tree, skipping if source doesn't exist."""
    if not src.exists():
        return
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)


def render_windsurf(spec: Dict[str, Any], spec_dir: Path) -> str:
    """Render Windsurf workflow markdown (PRIMARY target)."""
    name = spec["name"]
    desc = spec.get("description", "")
    
    lines = [
        "---",
        f"description: {desc}",
        "auto_execution_mode: 3",
        "---",
        "",
        f"# {name}",
        "",
        f"{desc}",
        "",
    ]
    
    # Triggers
    triggers = spec.get("triggers", [])
    if triggers:
        lines.append("## Triggers")
        lines.append("")
        for t in triggers:
            lines.append(f"- {t}")
        lines.append("")
    
    # Prerequisites (check for scripts)
    scripts = spec.get("scripts", [])
    if scripts:
        lines.append("## Prerequisites")
        lines.append("")
        lines.append("```bash")
        lines.append("python3 --version || python --version")
        lines.append("```")
        lines.append("")
    
    # Workflow
    lines.append("## Workflow")
    lines.append("")
    workflow = spec.get("workflow", {})
    workflow_type = workflow.get("type", "sequential")
    lines.append(f"Mode: `{workflow_type}`")
    lines.append("")
    
    steps = workflow.get("steps", [])
    for i, step in enumerate(steps, 1):
        title = step.get("title", f"Step {i}")
        kind = step.get("kind", "action")
        kind_badge = "🚦 GATE" if kind == "gate" else ""
        
        lines.append(f"### Step {i}: {title} {kind_badge}")
        lines.append("")
        
        notes = step.get("notes", "")
        if notes:
            # Expand references paths
            notes = notes.replace("`references/", f"`skills/{name}/references/")
            lines.append(notes)
            lines.append("")
        
        commands = step.get("commands", [])
        if commands:
            lines.append("```bash")
            for cmd in commands:
                lines.append(cmd)
            lines.append("```")
            lines.append("")
    
    # Resources
    refs = spec.get("references", [])
    if refs:
        lines.append("## References")
        lines.append("")
        for ref in refs:
            ref_path = f"skills/{name}/{ref}"
            lines.append(f"- `{ref_path}`")
        lines.append("")
    
    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*Generated by skill-creator. Source: `skills/{}/skillspec.json`*".format(name))
    
    return "\n".join(lines)


def render_claude(spec: Dict[str, Any], spec_dir: Path) -> str:
    """Render Claude SKILL.md (backward compat, strict frontmatter)."""
    name = spec["name"]
    desc = spec.get("description", "")
    
    lines = [
        "---",
        f"name: {name}",
        f"description: {desc}",
        "---",
        "",
        f"# {name}",
        "",
        "## What this skill does",
        "",
        desc,
        "",
    ]
    
    triggers = spec.get("triggers", [])
    if triggers:
        lines.append("## When to use")
        lines.append("")
        for t in triggers:
            lines.append(f"- {t}")
        lines.append("")
    
    questions = spec.get("questions", [])
    if questions:
        lines.append("## Requirement collection (at most 10 questions)")
        lines.append("")
        for i, q in enumerate(questions, 1):
            lines.append(f"{i}. {q}")
        lines.append("")
    
    lines.append("## Workflow")
    lines.append("")
    workflow = spec.get("workflow", {})
    for i, step in enumerate(workflow.get("steps", []), 1):
        title = step.get("title", f"Step {i}")
        kind = step.get("kind", "action")
        lines.append(f"### {i}. {title}" + (" (GATE)" if kind == "gate" else ""))
        notes = step.get("notes", "")
        if notes:
            lines.append(notes)
        commands = step.get("commands", [])
        if commands:
            lines.append("```bash")
            lines.extend(commands)
            lines.append("```")
        lines.append("")
    
    return "\n".join(lines)


def render_cursor(spec: Dict[str, Any], spec_dir: Path) -> str:
    """Render Cursor command markdown (backward compat)."""
    name = spec["name"]
    desc = spec.get("description", "")
    
    lines = [f"# {name}", "", desc, ""]
    
    triggers = spec.get("triggers", [])
    if triggers:
        lines.append("## When to use")
        for t in triggers:
            lines.append(f"- {t}")
        lines.append("")
    
    lines.append("## Steps")
    lines.append("")
    workflow = spec.get("workflow", {})
    for i, step in enumerate(workflow.get("steps", []), 1):
        lines.append(f"{i}. {step.get('title', 'Step')}")
    
    return "\n".join(lines)


def render_github(spec: Dict[str, Any], spec_dir: Path) -> str:
    """Render GitHub Skills SKILL.md (backward compat)."""
    name = spec["name"]
    desc = spec.get("description", "")
    
    lines = [
        "---",
        f"name: {name}",
        f"description: {desc}",
        "compatibility: Multi-assistant (Claude/Windsurf/Cursor/GitHub)",
        "---",
        "",
        f"# {name}",
        "",
        desc,
        "",
    ]
    
    workflow = spec.get("workflow", {})
    lines.append("## Workflow")
    lines.append("")
    for i, step in enumerate(workflow.get("steps", []), 1):
        lines.append(f"### {i}. {step.get('title', 'Step')}")
        if step.get("notes"):
            lines.append(step["notes"])
        lines.append("")
    
    return "\n".join(lines)


def generate_target(spec: Dict[str, Any], spec_dir: Path, target: str, repo_root: Path) -> Path:
    """Generate output for a specific target."""
    name = spec["name"]
    
    if target == "windsurf":
        content = render_windsurf(spec, spec_dir)
        out_path = repo_root / ".windsurf" / "workflows" / f"{name}.md"
    elif target == "claude":
        content = render_claude(spec, spec_dir)
        out_path = repo_root / ".claude" / "skills" / name / "SKILL.md"
    elif target == "cursor":
        content = render_cursor(spec, spec_dir)
        out_path = repo_root / ".cursor" / "commands" / f"{name}.md"
    elif target == "github":
        content = render_github(spec, spec_dir)
        out_path = repo_root / ".github" / "skills" / name / "SKILL.md"
    else:
        raise ValueError(f"Unknown target: {target}")
    
    ensure_dir(out_path.parent)
    out_path.write_text(content, encoding="utf-8")
    
    # Copy resources for Claude and GitHub (they need local copies)
    if target in ("claude", "github"):
        res_dst = out_path.parent / "resources"
        copytree_safe(spec_dir / "references", res_dst / "references")
        copytree_safe(spec_dir / "scripts", res_dst / "scripts")
        copytree_safe(spec_dir / "assets", res_dst / "assets")
    
    return out_path


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate multi-assistant outputs from skillspec.json")
    parser.add_argument("spec", help="Path to skillspec.json")
    parser.add_argument("--target", "-t", choices=["windsurf", "claude", "cursor", "github"],
                        help="Generate for specific target (default: windsurf)")
    parser.add_argument("--all", "-a", action="store_true", help="Generate for all targets")
    parser.add_argument("--repo-root", "-r", default=str(REPO_ROOT), help="Repository root")
    
    args = parser.parse_args()
    
    spec_path = Path(args.spec).resolve()
    repo_root = Path(args.repo_root).resolve()
    
    if not spec_path.exists():
        print(f"Spec not found: {spec_path}", file=sys.stderr)
        sys.exit(1)
    
    spec = load_spec(spec_path)
    spec_dir = spec_path.parent
    
    if args.all:
        targets = ["windsurf", "claude", "cursor", "github"]
    else:
        targets = [args.target or "windsurf"]
    
    for target in targets:
        out_path = generate_target(spec, spec_dir, target, repo_root)
        print(f"Generated: {out_path}")


if __name__ == "__main__":
    main()
